"""create automations and tasks

Revision ID: c0c487d5e8e7
Revises: d914194731a0
Create Date: 2026-09-06 02:43:13.665006

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c0c487d5e8e7'
down_revision = 'd914194731a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('trigger_type', sa.Text(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('cron_expression', sa.Text(), nullable=True),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('action_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automations_status_next_run_at', 'automations', ['status', 'next_run_at'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('automation_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_automation_id_created_at', 'tasks', ['automation_id', 'created_at'], unique=False)
    # NOTE: autogenerate wanted to drop ix_memories_embedding_hnsw here (same
    # spurious diff as the agent_runs/tool_executions migration -- it's a raw-SQL
    # index not represented in SQLAlchemy's metadata). Intentionally omitted.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_automation_id_created_at', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_automations_status_next_run_at', table_name='automations')
    op.drop_table('automations')
    # ### end Alembic commands ###
